version: '3'
services:
  shop-tracker:
    build: .
    image: shop-tracker
    environment:
      GRAPHQL_SERVER: http://localhost:3000/graphql
      MONGO_URI: mongodb://mongo:27017/shop-tracker
      PORT: 3000
    ports:
      - '80:3000'
    depends_on: [mongo]
  mongo:
    image: mongo
    ports:
      - '27017:27017'
